### ISSUE TITLE
Contents language

### ISSUE THREAD

**Issue by ericsagnes** [Tokyo-NixOS/Tokyo-NixOS-Meetup-Wiki#2]
Shall we make the contents in english, japanese or both?

cc @yugawara

**Comment by yugawara** [comment]
both?  but im open, in any way - man nixos is really cool i think we will do so well with this.

**Comment by ericsagnes** [comment]
Thanks!
Let's add both then.

Regarding the naming convention:
- japanese: normal name - `my-page.md`
- english: add `_en` to japanese name - `my-page_en.md`

as a sample I added a page about module customization:

https://github.com/Tokyo-NixOS/Tokyo-NixOS-Meetup-Wiki/blob/master/pages/module_en.md

Feel free to add or correct any content!
