### ISSUE TITLE
Why can't define user with declarative style?

### ISSUE THREAD

**Issue by master-q** [Tokyo-NixOS/Tokyo-NixOS-Meetup-Wiki#3]
I read following chapter:

http://nixos.org/nixos/manual/#sec-user-management

But I can't define my user with declarative style. How to do that?

**Comment by ericsagnes** [comment]
You have to put the user definition in `/etc/nixos/configuration.nix` and then rebuild with `nixos-rebuild switch` (as root)

sample:

``` nix
{ config, pkgs, ... }:
{
  users.extraUsers.nixuser = {
    isNormalUser = true;
    createHome = true;
    extraGroups = [ "wheel" ];
    uid = 1000;
  };
}
```

**Comment by master-q** [comment]
Thanks. I forget run `nixos-rebuild switch`.
