### ISSUE TITLE
nix-channel option 修正

### ISSUE THREAD

**Issue by ericsagnes** [Tokyo-NixOS/Tokyo-NixOS-Meetup-Wiki#4]
@igrep さん
wikiのコミット履歴はわかりにくいので、issueで書きます。

先ほどのwikiの修正は`nix-env`を`nix-channel`と勘違いした気がします。

少しややこしいです:
- `nix-env`は`--upgrade`を使う。[マニュアル](http://nixos.org/nix/manual/#operation-upgrade)
- `nix-channel`は`--update`を使う。[マニュアル](http://nixos.org/nix/manual/#sec-nix-channel)

**Comment by igrep** [comment]
すみません。ちょっと勘違いしてました。。。
:bow:
